### ISSUE TITLE
Mapping Date and excluding fields inside objects.

### ISSUE THREAD

**Issue by teebu** [acupofjose/elasticstore#26]
How do I map date?

I have this in references.ts
```
collection: "comments",
    index: "comments",
    mappings: {
      created_at: {
        type: "date" 
      }
    },
```

But it creates this mapping in ES:
```
"updated_at":{"properties":{"_nanoseconds":{"type":"long"},"_seconds":{"type":"long"}}}
```

Which looks like this in the index:
```
updated_at: {
  _seconds: 1580327708,
  _nanoseconds: 371000000,
},
```

The data is of type `timestamp` in Firestore. 

### 2nd question:
If I have a field inside another object:
`comment.something.foo` and I want to exclude `foo`. How would I do that? Is that something I use transform for and not the exclude array? Can I give it the full path in the array as string?

**Comment by acupofjose** [comment]
@teebu, that is because of the way that Firestore now handles timestamps. Instead of it being your standard js date object, it is a property map (as you're currently seeing).

If you really need it to be a js date object, you can utilize the `transform` function property in your `reference`. 

Something like: `transform: (firestoreDoc) => {...firestoreDoc, updated_at: firestoreDoc.updated_at.toDate() }`

As to your second question, you could use transform to exclude that. At the moment, all `exclude` can do is top-level keys. You make a good case for a change to that though!

**Comment by teebu** [comment]
I'm using this to check if timestamp is a timestamp, is there a better way?

```
created_at: data.created_at && typeof data.created_at == 'object' && data.created_at.toDate() || null, 
```
